name: .NET Provisioner New System Test
on: push

env: 
  DOTNET_VERSION: '6.0'

jobs: 
  dotnet-provisioner-aca-test-ubuntu:
    name: Setup ACA and Test Provisioner Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: ubuntu-20.04
         #- os: ubuntu-18.04
    continue-on-error: false
    outputs:
      output1: ${{ steps.ubuntu_result.outputs.result }}
    steps:
      - name: Setup tmate session
        if: success() || failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: System Test Setup
        run: |
          # Change dash to bash
          sudo echo "dash dash/sh boolean false" | sudo debconf-set-selections
          sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
          export RUNLEVEL=1
          
          # Authenticate
          echo "${{ secrets.PKG_PWD }}" | docker login ghcr.io -u $ --password-stdin;
          
          # Setup env
          sudo mkdir -p /mnt/hirs-ci/{builds,logs}
          sudo chmod -R 777 /mnt/hirs-ci
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Run tests"
        run: |
          pwd
          ls
          cd .ci/compose
          sh ./runner.sh
          
