name: .NET Provisioner New System Test
on: push

env: 
  DOTNET_VERSION: '6.0'

jobs: 
  dotnet-provisioner-aca-test-ubuntu:
    name: Setup ACA and Test Provisioner Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: ubuntu-20.04
         #- os: ubuntu-18.04
    continue-on-error: false
    outputs:
      output1: ${{ steps.ubuntu_result.outputs.result }}
    steps:
      - name: System Test Setup
        run: |
          echo "${{ secrets.PKG_PWD }}" | docker login ghcr.io -u $ --password-stdin;
          sudo mkdir -p /mnt/hirs-ci/{builds,logs,repos}
          sudo chmod -R 777 /mnt/hirs-ci
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          path: /mnt/hirs-ci/repos/
      - name: "Run tests"
        run: |
          cd /mnt/hirs-ci/repos/HIRS/.ci/compose
          sh ./.ci/compose/runner.sh
          
