# Sets up and runs HIRS System tests

name: HIRS System Tests
on: 
  push:
  workflow_dispatch:
env:
  TEST_STATUS: 0
jobs:
  DockerTests:
    if: "!contains(github.event.commits[0].message, '[dotnet only]')"
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.set_outputs.outputs.test-result }}
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file  
    - name: ACA TPM2 Tests
      continue-on-error: true
      shell: bash
      run: |
        sudo apt-get install -y curl
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        bash .ci/system-tests/run_system_tests.sh
    - name: Archive System Test Log files
      uses: actions/upload-artifact@v2
      with:
        name: System_Test_Log_Files
        path: logs/
        if-no-files-found: error
    - name: Check System Test results
      if: success() || failure()
      run: |
        if [ ${TEST_STATUS} == "0" ]; then
          exit 0;
        else
          exit 1;
        fi