name: Windows-based Building, Unit and System Tests
on: push

env:
  DOTNET_VERSION: '6.0'

jobs:
  windows-builder:
    name: 
    runs-on: ${{ matrix.os }} # currently only planning to target one OS
    strategy:                 # leaving this in case support for newer
      matrix:                 # options is as easy as adding them here
        include:              # (not likely)
         - os: windows-2022
    continue-on-error: true
    steps:
      - name: Set git autocrlf to false # to avoid line ending issues
        run: |
          git config --global core.autocrlf false
      - name: Force use of .NET 6 # several statements below assume .NET 6
        run: |
          dotnet new globaljson --sdk-version 6 --force
      - name: Install dotnet packaging tools
        run: |
          dotnet tool install --global dotnet-rpm
          dotnet tool install --global dotnet-deb
      - name: Add dotnet tools directory to PATH
        run: |
          Add-Content $env:GITHUB_PATH "~/.dotnet/tools"
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Unit Tests
        run: |
          cd HIRS_Provisioner.NET
          dotnet restore
          dotnet test
      - name: Build and publish the .NET Provisioner for Windows
        run: |
          cd HIRS_Provisioner.NET/hirs
          dotnet publish -r win-x64 -c Release --self-contained
      - name: Build and publish the .NET Provisioner for Linux
        run: | 
          cd HIRS_Provisioner.NET/hirs
          dotnet publish -r linux-x64 -c Release --self-contained
      - name: Build the .NET Provisioner MSI Artifact
        id: dotnet_provisioner_build_msi
        run: |
          cd HIRS_Provisioner.NET/hirs
          dotnet msbuild hirs.csproj /t:Msi /P:TargetFramework=net6.0 /p:RuntimeIdentifier=win-x64 /p:Configuration=Release
          ls bin/Release/net6.0/win-x64/*.msi
          Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem "bin/Release/net6.0/win-x64/*.msi")
          ls bin/Release/net6.0/win-x64/publish
      - name: Build the .NET Provisioner RPM Artifact
        id: dotnet_provisioner_build_rpm
        run: |
          cd HIRS_Provisioner.NET/hirs
          dotnet rpm -r linux-x64 -c Release
          ls bin/Release/net6.0/linux-x64/
          Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem "bin/Release/net6.0/linux-x64/*.rpm")
          ls bin/Release/net6.0/linux-x64/publish
      - name: Build the .NET Provisioner DEB Artifact
        id: dotnet_provisioner_build_deb
        run: |
          cd HIRS_Provisioner.NET/hirs
          dotnet deb -r linux-x64 -c Release
          ls bin/Release/net6.0/linux-x64/*.deb
          Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem "bin/Release/net6.0/linux-64/*.deb")
          ls bin/Release/net6.0/linux-x64/publish
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v3
        if: steps.dotnet_provisioner_build_msi.outcome == 'success'
        with:
          name: hirs.msi
          path: HIRS_Provisioner.NET/hirs/bin/Release/net6.0/win-x64/hirs.msi
      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v3
        if: steps.dotnet_provisioner_build_rpm.outcome == 'success'
        with:
          name: hirs.rpm
          path: HIRS_Provisioner.NET/hirs/bin/Release/net6.0/linux-x64/*.rpm
      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        if: steps.dotnet_provisioner_build_deb.outcome == 'success'
        with:
          name: hirs.deb
          path: HIRS_Provisioner.NET/hirs/bin/Release/net6.0/linux-x64/*.deb
      - name: Setup tmate session on error
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5 # The ssh session will be available for 5 minutes.
        with:
          limit-access-to-actor: true # Only the person who pushed can access- with a github-registered key.

